apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ndi
  namespace: ndi
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - savenemo.do-2023.fr
    secretName: ndi-tls
  rules:
  - host: savenemo.do-2023.fr
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: ndi
            port: 
              number: 80