name: CI
on:
  push:
    branches:
      - "*"
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with: 
          version: latest
      - run: pnpm install
      - run: pnpm lint
      - run: pnpm test
